CODE_NAME_PRIVATBANK = 'CODE_NAME_PRIVATBANK'

CODE_NAME_ALFABANK = 'CODE_NAME_ALFABANK'

CODE_NAME_MONOBANK = 'CODE_NAME_MONOBANK'

CODE_NAME_UKRGASBANK = 'CODE_NAME_UKRGASBANK'

CODE_NAME_OTPBANK = 'CODE_NAME_OTPBANK'

CODE_NAME_VKURSE_DP_UA = 'CODE_NAME_VKURSE_DP_UA'

CACHE_KEY_LATEST_RATES = 'currency::views::LatestRatesView::latest-rates'
