# Generated by Django 3.2.5 on 2021-07-21 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_auto_20210710_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodCafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cafe_name', models.CharField(max_length=35)),
                ('open_time', models.CharField(max_length=9)),
                ('close_time', models.CharField(max_length=9)),
                ('address', models.CharField(max_length=50)),
                ('recommended_menu', models.CharField(max_length=50)),
            ],
        ),
    ]
