# Generated by Django 3.2.5 on 2021-08-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0007_responselog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='type',
            field=models.CharField(choices=[('USD', 'Dollar'), ('EUR', 'Euro')], max_length=3),
        ),
        migrations.AlterField(
            model_name='responselog',
            name='response_time',
            field=models.PositiveSmallIntegerField(help_text='in milliseconds'),
        ),
    ]
