# Generated by Django 3.2.5 on 2021-09-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0010_responselog_request_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='logo',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
